# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PunchIn

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Punch In
      run: |
        sudo cp -p ./chromedriver /usr/bin/
        chmod -R 777 /usr/bin/chromedriver
        python ./FuckZJUnCovPunchIn.py 1${{secrets.USERNAME}} 2${{secrets.PASSWORD}} 3${{secrets.URL}} 4${{secrets.PROVINCE}} 5${{secrets.CITY}} 6${{secrets.DISTRICT}} 7${{secrets.ATSCHOOL}}
